name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start databases
        run: |
          docker compose up -d postgresdb redis

      - name: Wait for Postgres to be ready
        run: |
          until docker compose exec postgresdb pg_isready -U postgres; do
            echo "Waiting for postgres...";
            sleep 5;
          done

      - name: Install dependencies
        run: npm ci

      - name: No telemetry
        run: npm run disable-telemetry

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/main" >> $GITHUB_ENV
          echo "REDIS_URL=redis://127.0.0.1:6379" >> $GITHUB_ENV
          echo "SESSION_SECRET=change_me_to_a_longer_secret_for_ci" >> $GITHUB_ENV
          echo "TOKENS_ENCRYPTION_KEY=someRandomString32SymbolsLength!" >> $GITHUB_ENV
          echo "TELEGRAM_TOKENS_REFRESH_INTERVAL_SEC=60" >> $GITHUB_ENV
          echo "TELEGRAM_TOKENS_REFRESH_BEFORE_SEC=180" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=test_token" >> $GITHUB_ENV

      - name: Build
        run: NODE_ENV=production npm run build

      - name: Migrate database
        run: npm run migrate-apply

      - name: Run tests
        run: npm run test:ci
